-- Deliberately separate from games/player_game_stats and all training relations.
CREATE TABLE preparation_games (
    preparation_game_id VARCHAR PRIMARY KEY,
    season_code VARCHAR NOT NULL,
    game_date TIMESTAMPTZ NOT NULL,
    game_type VARCHAR NOT NULL CHECK (game_type IN ('FRIENDLY','PRESEASON_TOURNAMENT','SUPERCUP','DOMESTIC_OFFICIAL')),
    source VARCHAR NOT NULL,
    source_game_id VARCHAR NOT NULL,
    home_team_name VARCHAR NOT NULL,
    away_team_name VARCHAR NOT NULL,
    source_artifact_id VARCHAR NOT NULL REFERENCES raw_artifacts(artifact_id),
    ingestion_run_id VARCHAR NOT NULL REFERENCES ingestion_runs(run_id),
    UNIQUE(source, source_game_id)
);
CREATE TABLE preparation_player_stats (
    preparation_player_stat_id VARCHAR PRIMARY KEY,
    preparation_game_id VARCHAR NOT NULL REFERENCES preparation_games(preparation_game_id),
    canonical_player_id VARCHAR REFERENCES players(canonical_player_id),
    canonical_team_id VARCHAR REFERENCES teams(canonical_team_id),
    player_name_raw VARCHAR NOT NULL,
    team_name_raw VARCHAR NOT NULL,
    source_player_id VARCHAR NOT NULL,
    mapping_method VARCHAR NOT NULL,
    minutes DOUBLE CHECK (minutes BETWEEN 0 AND 80),
    starter BOOLEAN,
    points INTEGER,
    two_points_made INTEGER,
    two_points_attempted INTEGER,
    three_points_made INTEGER,
    three_points_attempted INTEGER,
    free_throws_made INTEGER,
    free_throws_attempted INTEGER,
    offensive_rebounds INTEGER,
    defensive_rebounds INTEGER,
    total_rebounds INTEGER,
    assists INTEGER,
    steals INTEGER,
    turnovers INTEGER,
    blocks INTEGER,
    blocks_received INTEGER,
    fouls_committed INTEGER,
    fouls_drawn INTEGER,
    pir DOUBLE,
    efficiency DOUBLE,
    plus_minus INTEGER,
    source_artifact_id VARCHAR NOT NULL REFERENCES raw_artifacts(artifact_id),
    ingestion_run_id VARCHAR NOT NULL REFERENCES ingestion_runs(run_id),
    UNIQUE(preparation_game_id, team_name_raw, source_player_id)
);
